discuss/urls.py
from django.conf.urls import patterns, include, url
from views import (ThreadDetail, ThreadCreate, ThreadUpdate, ThreadDelete, ThreadList, 
                    CategoryDetail, CategoryUpdate, CategoryDelete, CategoryList, CategoryCreate, 
                    ChallengeDetail, ChallengeUpdate, ChallengeDelete, ChallengeList, ChallengeCreate, 
                    TagList, TagDetail, thread_challenge_view)
from lars import settings
import models, forms


newspatterns = patterns('',
    url(r'^s?/?$', CategoryDetail.as_view(), {'pk':settings.NEWS_CATEGORY_PK}, name='list'),
    url(r'^/(?P<pk>\d+)/?$', ThreadDetail.as_view(), name='view'),
    url(r'^/(?P<pk>\d+)/update/?$', ThreadUpdate.as_view(form_class=forms.NewsForm), name='update'),
    url(r'^/create/?$', ThreadCreate.as_view(form_class=forms.NewsForm), name='create'),
    url(r'^/(?P<thread_pk>\d+)/challenge/?$', thread_challenge_view, name='attach_challenge'),
)

threadpatterns = patterns('',
    url(r'^s?/?$', CategoryList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/?$', ThreadDetail.as_view(), name='view'),
    url(r'^/(?P<pk>\d+)/update/?$', ThreadUpdate.as_view(), name='update'),
    url(r'^/(?P<pk>\d+)/delete/?$', ThreadDelete.as_view(), name='delete'),
    url(r'^/create/?$', ThreadCreate.as_view(), name='create'),
    url(r'^/(?P<thread_pk>\d+)/challenge/?$', thread_challenge_view, name='attach_challenge'),
    url(r'^/search/?$', ThreadList.as_view(), {'search':True}, name='search'),
)

forumpatterns = patterns('',
    url(r'^s?/?$', CategoryList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/?$', CategoryDetail.as_view(), name='view'),
    url(r'^/(?P<pk>\d+)/?$', CategoryUpdate.as_view(), name='update'),
    url(r'^/(?P<pk>\d+)/?$', CategoryDelete.as_view(), name='delete'),                         
    url(r'^/create/?$', CategoryCreate.as_view(), name='create'),
    url(r'^/search/?$', ThreadList.as_view(), {'search':True}, name='search'),
)

challengepatterns = patterns('',
    url(r'^s?/?$', ChallengeList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/?$', ChallengeDetail.as_view(), name='view'),
    url(r'^/(?P<pk>\d+)/update/?$', ChallengeUpdate.as_view(), name='update'),
    url(r'^/(?P<pk>\d+)/delete/?$', ChallengeDelete.as_view(), name='delete'),                         
)

tagpatterns = patterns('', 
    url(r'^s?/?$', TagList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/?$', TagDetail.as_view(), name='view'),
)

lars/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
from django.contrib import admin
from django.views.generic import TemplateView
from discuss.urls import threadpatterns, forumpatterns, challengepatterns, tagpatterns, newspatterns
from discuss.views import CategoryDetail, ThreadCreate
from entry.urls import deckpatterns, votepatterns
from entry.views import DeckList
from moderation.urls import modpatterns

admin.autodiscover()

urlpatterns = patterns('',
    #home page
    url(r'^/?$', 'lars.views.viewHome', name='view_home'),
    #admin page
    url(r'^admin/', include(admin.site.urls)),
    #Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #various app urls
    #entry
    url(r'^deck', include(deckpatterns, app_name='entry', namespace='deck')),
    #vote
    url(r'^vote', include(votepatterns, app_name='entry', namespace='vote')),
    #other apps
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/mod_flagged/?$', 'lars.views.flaggedComments_view', name='view_flagged_comments'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    #discuss
    url(r'^news', include(newspatterns, app_name='discuss', namespace='news')),
    url(r'^thread', include(threadpatterns, app_name='discuss', namespace='thread')),
    url(r'^forum', include(forumpatterns, app_name='discuss', namespace='forum')),
    url(r'^challenge', include(challengepatterns, app_name='discuss', namespace='challenge')),
    url(r'^tag', include(tagpatterns, app_name='discuss', namespace='tag')),
    #moderation
    url(r'^moderation', include(modpatterns, app_name='moderation', namespace='mod')),
    #account-related urls
    url(r'^user/(?P<pk>\d+)/?$', 'lars.views.viewUser', name='view_user_profile'),
    url(r'^login/?$', 'lars.views.login_view', name='login_page'),
    url(r'^logout/?$', 'lars.views.logout_view', name='logout_page'),
    url(r'^account_disabled/?$', 'lars.views.accountDisabled_view', name='account_disabled_page'),
    url(r'^register/?$', 'lars.views.registration_view', name='registration_page'),
    url(r'^register/success.html$', TemplateView.as_view(template_name='registration_success.html'), name='registration_successful_page'),
    url(r'^prefs/?$', 'lars.views.preferences_view', name='preferences_page'),
    #static pages
    url(r'^about/?$', TemplateView.as_view(template_name='about.html'), name='about_page'),
    url(r'^contact/?$', TemplateView.as_view(template_name='contact.html'), name='contact_page'),
)


if getattr(settings, 'DEBUG', False) or getattr(settings, 'DEBUG_MEDIA', False):
    murl = getattr(settings, 'MEDIA_URL', '/media/').lstrip('/')
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % murl, 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT })
    )
    
urlpatterns += staticfiles_urlpatterns()

discuss/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models.signals import post_delete
from django.contrib.comments import Comment
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericRelation
from django.core.exceptions import ValidationError
from django.contrib.contenttypes import generic
from datetime import datetime
from django.utils.timezone import now, make_aware, utc

class ThreadManager(models.Manager):
    def get_by_natural_key(self, title, date_posted):
        return self.get(title=title, date_posted=date_posted)

class PublicSetManager(ThreadManager):
    def get_query_set(self):
        return super(PublicSetManager, self).get_query_set().filter(is_public=True, is_removed=False)

class TagManager(models.Manager):
    def get_by_natural_key(self, text):
        return self.get(text=text)

class CategoryManager(models.Manager):
    def get_by_natural_key(self, title):
        return self.get(title=title)

class RequirementManager(models.Manager):
    def get_by_natural_key(self, text):
        return self.get(text=text)

class BinaryPollManager(models.Manager):
    def get_by_natural_key(self, question, object_id, content_type):
        return self.get(question=question, object_id=object_id, content_type=content_type)



class Tag(models.Model):
    text = models.CharField(max_length=64, unique=True)
    objects = TagManager()
    def __unicode__(self):
        return self.text
    def clean(self):
        if not self.text:
            raise forms.ValidationError('Requirement cannot have empty text')
        super(Tag, self).clean()
    def get_absolute_url(self):
        pass
    def natural_key(self):
        return self.text

class Category(models.Model):
    title = models.CharField(max_length=128, unique=True)
    description = models.TextField()
    restricted = models.CharField(max_length=128, blank=True, null=True) #permission string to restrict access
    objects = CategoryManager()
    def clean(self):
        if not self.title.lstrip():
            raise forms.ValidationError('Category must have nonempty title')
        if not self.description.lstrip():
            raise forms.ValidationError('Category must have nonempty description')
        super(Category, self).clean()
    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('forum_view', kwargs={'pk':str(self.pk)})
    def natural_key(self):
        return self.title

class Thread(models.Model):
    creator = models.ForeignKey(User)
    title = models.CharField(max_length=256)
    text = models.TextField()
    comments_enabled = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT) #perhaps try a query with Models.SET()
    date_posted = models.DateTimeField(auto_now_add=True)
    date_published = models.DateTimeField(default=now)
    is_public = models.BooleanField(default=True, blank=True)
    is_removed = models.BooleanField(default=False, blank=True)
    comments = GenericRelation(Comment, object_id_field="object_pk")
    #needs date_modified
    #managers
    objects = ThreadManager()
    public = PublicSetManager()
    #private = PrivateThreadManager()
    #removed = RemovedThreadManager()
    def clean(self):
        if self.is_public == True and self.is_removed == True:
            raise ValidationError('Removed threads cannot also be public.')
        super(Thread, self).clean()
    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('thread:view', kwargs={'pk':str(self.pk)})
    def is_published(self):
        return (self.date_published.replace(tzinfo=utc) - now()).total_seconds() <= 0 #is today >= date_published


class Requirement(models.Model):
    text = models.CharField(max_length=255, unique=True)
    objects = RequirementManager()
    def clean(self):
        if not self.text:
            raise forms.ValidationError('Requirement cannot have empty text')
        super(Requirement, self).clean()
    def __unicode__(self):
        return self.text
    def get_absolute_url(self):
        pass
    def natural_key(self):
        return self.text

class Challenge(models.Model):
    title = models.CharField(max_length=255)
    date_expires = models.DateTimeField()
    news = models.ForeignKey(Thread)
    recs = models.ManyToManyField(Requirement)
    #since challenges remain in DB past expiration should note on boards if challenge is expired - perhaps even discontinue voting?
    def clean(self):
        #validating date_expires will require more knowledge of tz, dst and the datetime module
        super(Challenge, self).clean()
    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return self.news.get_absolute_url()
    def natural_key(self):
        return (self.title,) + self.news.natural_key()
    natural_key.dependencies = ['discuss.thread']


class BinaryPoll(models.Model):
    question = models.CharField(max_length=128)
    yes = models.ManyToManyField(User, related_name='yes_votes')
    no = models.ManyToManyField(User, related_name='no_votes')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    poll = generic.GenericForeignKey('content_type', 'object_id')
    objects = BinaryPollManager()
    def __unicode__(self):
        return "%s (%i:%i)" % (self.question, self.yes.all().count(), self.no.all().count())
    def get_absolute_url(self):
        return self.poll.get_absolute_url()
    #def add_to_tes(self, user):
    #    self.yes.add(user)
    #    if self.yes.
    def yes_count(self):
        if not hasattr(self, 'yesses'):
            self.yesses = self.yes.all().count()
        return self.yesses
    def no_count(self):
        if not hasattr(self, 'nos'):
                self.nos = self.no.all().count()
        return self.nos
    def user_voted(self, user):
        if user in self.yes.all() or user in self.no.all(): return True
        else: return False
    def get_vote_for_user(self, user):
        if user in self.yes.all():
            return True
        if user in self.no.all():
            return False
    def natural_key(self):
        return (self.question, self.object_id, self.content_type.natural_key())

discuss/forms.py
from django import forms
from models import Challenge, Thread, Tag, Requirement
from fields import clean_char_field

class ChallengeForm(forms.ModelForm):
    recs = forms.CharField(widget=forms.Textarea) #needs to be textarea
    news = forms.MultipleHiddenInput()
    class Meta():
        model = Challenge
    def clean_recs(self):
        return clean_char_field(self.cleaned_data, 'recs', '\n', Requirement)

class ThreadForm(forms.ModelForm):
    tags = forms.CharField() #how do we make this not required?
    class Meta():
        model = Thread
        fields = ('title', 'tags', 'text', 'comments_enabled', 'category')
    def clean_tags(self):
        return clean_char_field(self.cleaned_data, 'tags', ',', Tag)

class NewsForm(forms.ModelForm):
    tags = forms.CharField()
    ifchallenge = forms.CheckboxInput()
    class Meta():
            model = Thread
            fields = ('title', 'tags', 'text', 'comments_enabled', 'category', 'date_published')
    def clean_tags(self):
        return clean_char_field(self.cleaned_data, 'tags', ',', Tag)

lars/forms.py
from django import forms

class SearchForm(forms.Form):
    DATE_CHOICE = 'date_posted'
    CREATOR_CHOICE = 'creator'
    TITLE_CHOICE = 'title'
    ASC_CHOICE = 'asc'
    DESC_CHOICE = 'dsc'
    fulltext = forms.CharField(max_length="100", required=False)
    tags = forms.CharField(max_length="128", required=False)
    users = forms.CharField(max_length="128", required=False)
    date = forms.DateField(required=False)
    sort = forms.ChoiceField(((DATE_CHOICE, 'Date'), (CREATOR_CHOICE, 'Creator'), (TITLE_CHOICE, 'Title')), required=False)
    order = forms.ChoiceField(((ASC_CHOICE, 'Ascending'), (DESC_CHOICE, 'Descending')), widget=forms.RadioSelect, required=False)

moderation/views.py
# Create your views here.
import os
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.contenttypes.models import ContentType
from forms import ModEventForm
from models import ModEvent
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect

class ModEventDetail(DetailView):
    model = ModEvent
    
    def get_context_data(self, **kwargs):
        context = super(ModEventDetail, self).get_context_data(**kwargs)
        context['object_template'] = '%s%s%s_full_view.html' % (self.object.content_type.app_label, os.sep, self.object.content_type.model)
        context[self.object.content_type.model] = self.object.content_object
        return context
    
class ModEventList(ListView):
    model = ModEvent
    context_object_name = "modevent_list"

class ModEventCreate(CreateView):
    model = ModEvent
    form_class = ModEventForm

    def form_valid(self, form):
        form.instance.creator = self.request.user
        #form.instance.content_type = ContentType.objects.get_for_id(self.request.POST.get('content_type'))
        #form.instance.object_id = self.request.POST.get('object_id')
        #content_object = content_object
        #content_object = form.instance.content_type.get_object_for_this_type(pk=form.instance.object_id)
        #if content_object == None:
        #    raise ValueError
        form.instance.content_object.is_public = False
        form.instance.content_object.is_removed = True
        form.instance.content_object.save()
        return super(ModEventCreate, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['content_type'] = self.request.GET.get('content_type')
        context['object_id'] = self.request.GET.get('object_id')
        return context
        
    def get_success_url(self):
        return reverse('%s:list' % self.object.content_type.model) #we should edit this
        # we can easily access self.object.app_label and such to go to the list, but since entry uses "deck" for its urls, this will not work yet

class ModEventDelete(DeleteView):      
    model = ModEvent
    context_object_name = 'modevent'
    success_url = reverse_lazy('view_home')
    # this will check if the related object should be delteted as well, and respond accordingly
    # generally the corresponding object will be deleted too, but ocassionaly, for example when there are 
    # a ton of copies of the ModEvent object for a single action, that will not be the case (and could
    # cause errors if the model attempted such a thing)
    
    def get_context_object(self, **kwargs):
        context = super(ModEventDelete, self).get_context_object(**kwargs)
        return context

    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        if self.request.POST.get('delete_associated_object', False):
            self.object.content_object.delete()
        else:
            self.object.content_object.is_public = True
            self.object.content_object.is_removed = False
            self.object.content_object.save()
        return HttpResponseRedirect(success_url)

lars/templates/discuss/category_detail.html
{% extends 'discuss/thread_list.html' %}

{% load comments %}

{% block title %}{{ forum.title }}{% if not news %} subforum{% endif %}{% endblock %}

{% block head_script %}{% endblock %}

{% block content %}
<h2 class="forum_name">{{ forum.title }}</h2>
<p class="forum_description">{{ forum.description }}</p>
{% if perms.discuss.add_thread %}
{% if "News" in forum.title %}
{% if perms.discuss.add_news %}
<a href="{% url news:create %}">Post News</a>
{% endif %}
{% else %}
<a href="{% url thread:create %}?referer={{forum.pk}}">Post Thread</a>
{% endif %}
{% endif %}
{% for thread in thread_list %}
{% get_comment_count for thread as comment_count %}
{% include 'discuss/thread_mini_view.html' %}
{% endfor %}
{% endblock %}

lars/templates/discuss/challenge_form.html
{% extends 'base.html' %}

{% block title %}Challenge the People!{% endblock %}

{% block content %}

<form name="challenge" action="" method="POST">
	{% csrf_token %}
	<div>{{ form.errors.title }}{{ form.title.label_tag }} {{ form.title }}</div>
	<div>{{ form.errors.recs }}{{ form.recs.label_tag }} {{ form.recs }}</div>
	<div>{{ form.errors.date_expires }}{{ form.date_expires.label_tag }} {{ form.date_expires }}</div>
	{{ form.errors.news }}<input type="hidden" name="news" value="{{ thread_pk }}" />
	<br />
	<input type="submit" value="Post!" /> <input type="reset" value="Clear" />
</form>
{% endblock %}

lars/templates/discuss/comment_list.html
{% extends 'base.html' %}

{% load comments %}

{% block title %}Useless Comment List{% endblock %}

{% block content %}
{% for comment in comment_list %}
<div class="comment">
	<span><a href="{% url view_user_profile comment.creator.pk %}">{{ comment.creator.username }}</a> posted in <a href="{% url thread_view comment.content_object. %}">{{ comment.response.content_object.title }}</a>{% endif %} on {{ comment.date_posted }} with:</span>
	<p>
		{{ comment.text }}
	</p>
	<span>(Last modified: {{ comment.date_modified }})</span>
</div>
{% endfor %}
{% endblock %}

lars/templates/discuss/forum_list.html
{% extends 'base.html' %}

{% block title %}Forums{% endblock %}
{% if perms.discuss.add_category %}
<a href="{% url forum:create %}">Create new forum category</a>
{% endif %}
{% block content %}
{% for forum in forum_list %}
<div class="forum_list_entry">
	<h3 class="forum_list_title"><a href="{% url forum:view forum.pk %}">{{ forum.title }}</h3></a>
	<p>{{ forum.description }}</p>
</div>
{% endfor %}
{% endblock %}

lars/templates/discuss/tag_detail.html
{% extends 'base.html' %}

{% block title %}{{ tag.text }}{% endblock %}

{% block content %}
	{% if tag.entry_set.all %}
	{% for entry in tag.entry_set.all %}
	<h2>Decks</h2>
		{% include 'entry/entry_mini.html' %}
	{% endfor %}
	{% endif %}


	{% if tag.thread_set.all %}
	{% for thread in tag.thread_set.all %}
	<h2>Threads</h2>
		{% include 'discuss/thread_mini_view.html' %}	
	{% endfor %}
	{% endif %}

{% endblock %}

lars/templates/discuss/thread_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete {{ thread.title }}?{% endblock %}

{% block content %}
</span>{{ thread.title }}<span> by {{ thread.creator.username }} on {# thread.date_modified #} (last modified {# thread.date_modified #})
<p>{{ thread.text }}</p>
<form method='POST' action'{% url thread:delete thread.pk %}'>
	{% csrf_token %}
	<button type='submit'>Delete</button>
</form>
<a href='{% url thread:view thread.pk %}'>Cancel</a>
{% endblock %}

lars/templates/discuss/thread_delete.html
{% extends 'base.html' %}
{% block title %}Delete {{ thread.title }}?{% endblock %}

{% block content %}
</span>{{ thread.title }}<span> by {{ thread.creator.username }} on {# thread.date_modified #} (last modified {# thread.date_modified #}
<p>{{ thread.text }}</p>
<form method='POST' target='{% url thread:delete %}'>
	<button type='submit'>Delete</button>
</form>
<a href='{% url thread:view thread.pk %}'>Cancel</a>
{% endblock %}

lars/templates/discuss/thread_detail.html
{% extends 'base.html' %}

{% load comments %}


{% block title %}{% if isnews %}News: {% endif %}{{ thread.title }}{% endblock %}

{% block head_script %}{% endblock %}


{% block content %}
<div id="page">
	{% include 'discuss/thread_full_view.html' %}
	{% if edit_button %}<a href="{% url thread:update thread.pk %}">Edit</a>{% endif %}
	{% if delete_button %}
		{% if perms.discuss.delete_thread %}
		<form action="{% url mod:create %}" method="GET" name="modform">
			<input type="hidden" name="content_type" value="{{ content_type }}" />
			<input type="hidden" name="object_id" value="{{ thread.pk }}" />
			<input type="submit" value="Delete" />	
		</form>
		{% else %}
		<a href="{% url thread:delete thread.pk %}">Delete</a>
		{% endif %}
	{% endif %}
	<section id="comments">
	<!-- Auth/comment system stuff... -->
	{% get_comment_list for thread as comment_list %}
	{% for comment in comment_list %}
		<span><a href='{% url view_user_profile comment.user.pk %}'>{{ comment.user.username }}</a> said: </span>
		<p>{{ comment.comment }}</p>
		<span>At {{ comment.submit_date }}</span>
	{% endfor %}
	{% if user.is_authenticated and thread.comments_enabled %}
	{% get_comment_form for thread as form %}
	<form action="{% comment_form_target %}" method="POST">
		{% csrf_token %}
		<input type="hidden" name="next" value="{% url thread:view thread.pk %}" />
		{{ form.comment }}
		{{ form.honeypot }}
		{{ form.content_type }}
		{{ form.object_pk }}
		{{ form.timestamp }}
		{{ form.security_hash }}
		<input type="submit" value="Post!" id="id_submit" />
	</form>
	{% else %}
		<p>Please <a href="{% url login_page %}" />login</a> to leave a comment. </p>
	{% endif %}
	</section>
</div>
{% endblock %}

lars/templates/discuss/thread_form.html
{% extends 'base.html' %}

{% block title %}Create new thread{% endblock %}

{% block head_script %}{% endblock %}

{% block content %}
<form name="thread" action="" method="POST">
	{{ form.non_field_errors }}
	{{ form.errors.category}}
	<div>{{ form.errors.title }}{{ form.title.label_tag }}{{ form.title }}</div>
	<div>{{ form.errors.text }}{{ form.text.label_tag }}{{ form.text }}</div>
	<div>{{ form.errors.tags }}{{ form.tags.label_tag }}{{ form.tags }}</div>
	{% if perms.discuss.disable_comments %}
	<div>{{ form.errors.comments_enabled }}{{ form.comments_enabled.label_tag }}{{ form.comments_enabled }}</div>
	{% endif %}
	{% if isnews %}
	<input type="hidden" id="id_category" value="{{ isnews }}" name="category" />
	<div>{{ form.errors.date_published }}{{ form.date_published.label_tag }}{{ form.date_published }}</div>
	{% else %}
	<div>{{ form.errors.category }}{{ form.category.label_tag }}<select id="id_category" name='category'>
			{% for cat in form.fields.category.queryset %}
			{% if 'News' not in cat.title or perms.news.add_news %}
			<option value="{{ cat.pk }}"{% if referer == cat.pk %} selected="selected"{% endif %}>{{ cat.title }}</option>
			{% endif %}
			{% endfor %}
		</select>
	</div>
	{% endif %}
	{% csrf_token %}
	<!-- The above permission should check to see if "News" category is allowed --> 
	{% if perms.challenge.add_challenge %}
	{% if isnews %}
	{% if not update %}
	Challenge: <input type="checkbox" name="ifchallenge" />
	{% endif %}
	{% endif %}
	{% endif %}
	<br />
	<input type="submit" value="Post!" /> <input type="reset" value="Clear" />
</form>
{% endblock %}

lars/templates/discuss/thread_full_view.html
<section id="announcement">
	<span id="title">{{ thread.title }}</span>
	<!--<img id="avvy" width="128px" height="128px" />-->
	<span id="thread_poster">Posted by <a href="{% url view_user_profile thread.creator.pk %}">{{ thread.creator.username }}</a> on {# dateposted here #}</span>
	<article id="text">{{ thread.text }}</article>
	{% if not moderation %}
		{% if thread.challenge_set.all %}{% with thread.challenge_set.all.0 as challenge %}
	<fieldset>
		<legend>{{ challenge.title }}</legend>
		<ul>{% for req in challenge.recs.all %}<li>{{ req.text }}</li>{% endfor %}</ul>
		{% if perms.discuss.change_challenge %}<a href="{% url challenge:update challenge.pk %}">Edit</a>{% endif %}
	</fieldset>
		{% endwith %}{% endif %}
	{% endif %}
	{% for tag in thread.tags.all %}<a class="tagLink" href="{% url tag:view tag.pk %}">{{ tag.text }}</a> {% endfor %}	
</section>	

lars/templates/discuss/thread_list.html
{% extends 'base.html' %}

{% block title %}Threads{% endblock %}

{% block content %}
{% if search %}
<form method="GET">
	{{ form.as_p }}
	<input type="hidden" name="filter" value="True" />
	<input type="submit" value="Submit!" /><input type="reset" value="Clear" />
</form>
{% endif %}


{% for thread in thread_list %}
	{% if not thread.is_removed %}
		{% if thread.is_public or perms.discuss.view_private %}
			{% include 'discuss/thread_mini_view.html' %}
		{% endif %}
	{% endif %}
{% endfor %}

{% endblock %}

lars/templates/discuss/thread_mini_view.html
<div class="thread_list_entry">
	<a href="{% url thread:view thread.pk %}">{{ thread.title }}</a> ({{ comment_count }}) Created by <a href="{% url view_user_profile thread.creator.pk %}">{{ thread.creator.username }}</a> on {# thread.date_posted #}
</div>