entry/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from views import DeckDetail, DeckList, DeckCreate, DeckUpdate, DeckDelete, searchView
import datetime

deckpatterns = patterns('',
    # entry object
    url(r'^s?/?$', DeckList.as_view(), name='list'),
    url(r'^/(?P<pk>\d+)/?$', DeckDetail.as_view(), name='view'),
    url(r'^/(?P<pk>\d+)/update/?$', DeckUpdate.as_view(), name='update'),
    url(r'^/(?P<pk>\d+)/delete/?$', DeckDelete.as_view(), name='delete'),
    url(r'^/create/?$', DeckCreate.as_view(),  name='create'),
    url(r'^/search/?$', DeckList.as_view(), {'search':True}, name='search'),
)

votepatterns = patterns('',
    url(r'/entry/(?P<pk>\d+)/?$', 'entry.views.vote', name='deck'), #send vote
    #vote list
)

#urlpatterns += staticfiles_urlpatterns()

lars/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
from django.contrib import admin
from django.views.generic import TemplateView
from discuss.urls import threadpatterns, forumpatterns, challengepatterns, tagpatterns, newspatterns
from discuss.views import CategoryDetail, ThreadCreate
from entry.urls import deckpatterns, votepatterns
from entry.views import DeckList
from moderation.urls import modpatterns

admin.autodiscover()

urlpatterns = patterns('',
    #home page
    url(r'^/?$', 'lars.views.viewHome', name='view_home'),
    #admin page
    url(r'^admin/', include(admin.site.urls)),
    #Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #various app urls
    #entry
    url(r'^deck', include(deckpatterns, app_name='entry', namespace='deck')),
    #vote
    url(r'^vote', include(votepatterns, app_name='entry', namespace='vote')),
    #other apps
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/mod_flagged/?$', 'lars.views.flaggedComments_view', name='view_flagged_comments'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    #discuss
    url(r'^news', include(newspatterns, app_name='discuss', namespace='news')),
    url(r'^thread', include(threadpatterns, app_name='discuss', namespace='thread')),
    url(r'^forum', include(forumpatterns, app_name='discuss', namespace='forum')),
    url(r'^challenge', include(challengepatterns, app_name='discuss', namespace='challenge')),
    url(r'^tag', include(tagpatterns, app_name='discuss', namespace='tag')),
    #moderation
    url(r'^moderation', include(modpatterns, app_name='moderation', namespace='mod')),
    #account-related urls
    url(r'^user/(?P<pk>\d+)/?$', 'lars.views.viewUser', name='view_user_profile'),
    url(r'^login/?$', 'lars.views.login_view', name='login_page'),
    url(r'^logout/?$', 'lars.views.logout_view', name='logout_page'),
    url(r'^account_disabled/?$', 'lars.views.accountDisabled_view', name='account_disabled_page'),
    url(r'^register/?$', 'lars.views.registration_view', name='registration_page'),
    url(r'^register/success.html$', TemplateView.as_view(template_name='registration_success.html'), name='registration_successful_page'),
    url(r'^prefs/?$', 'lars.views.preferences_view', name='preferences_page'),
    #static pages
    url(r'^about/?$', TemplateView.as_view(template_name='about.html'), name='about_page'),
    url(r'^contact/?$', TemplateView.as_view(template_name='contact.html'), name='contact_page'),
)


if getattr(settings, 'DEBUG', False) or getattr(settings, 'DEBUG_MEDIA', False):
    murl = getattr(settings, 'MEDIA_URL', '/media/').lstrip('/')
    urlpatterns += patterns('',
        url(r'^%s(?P<path>.*)$' % murl, 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT })
    )
    
urlpatterns += staticfiles_urlpatterns()

entry/models.py
from django.db import models
from thumbs import ImageWithThumbsField
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django import forms
from django.contrib.comments import Comment
from django.contrib.contenttypes.generic import GenericRelation
from discuss.models import Tag, Challenge, PublicSetManager, BinaryPoll
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Deck(models.Model):
    #information
    title = models.CharField(max_length=128)
    creator = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    text = models.TextField(blank=True, null=True)

    #record
    date_posted = models.DateField(auto_now_add=True)
    challenge = models.ForeignKey(Challenge, null=True, blank=True, on_delete=models.SET_NULL) #just one
    is_public = models.BooleanField(blank=True, default=True)
    is_removed = models.BooleanField(blank=True, default=False)

    #data
    deck_image = models.ImageField(upload_to="img/%Y/%m/%d")
    comments = GenericRelation(Comment, object_id_field="object_pk")
    polls = GenericRelation(BinaryPoll, object_id_field="object_id")
    deck_length_coefficient = models.SmallIntegerField()
    deck_width_coefficient = models.SmallIntegerField()

    #managers
    objects = models.Manager()
    public = PublicSetManager()

    class Meta():
        get_latest_by = 'date_posted'

    #methods
    def clean(self):
        #needs to check that any attached challenges are not expired
        if self.is_public == True and self.is_removed == True:
            raise ValidationError('Removed entries cannot also be public.')
        super(Deck, self).clean()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('deck:view', kwargs={'pk':str(self.pk)})

entry/forms.py
from discuss.fields import clean_char_field
from django import forms
from models import Deck
from discuss.models import Tag

class DeckForm(forms.ModelForm):
    tags = forms.CharField(required=False)
    deck_length_coefficient = forms.IntegerField(label="Length", initial='33')
    deck_width_coefficient = forms.IntegerField(label="Width", initial='9')
    class Meta():
        model = Deck
        fields = ('title', 'text', 'tags', 'challenge', 'deck_length_coefficient', 'deck_width_coefficient')
    def clean_tags(self):
        return clean_char_field(self.cleaned_data, 'tags', ',', Tag)

entry/views.py
from django.template import RequestContext
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from models import Deck
from forms import DeckForm
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.core.files.uploadedfile import SimpleUploadedFile
from django.views.generic import DetailView, ListView
import base64, datetime
from django.db.models import Q
from discuss.utils import searchQuerySet
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from lars.forms import SearchForm
from django.contrib.contenttypes.models import ContentType
from discuss.models import BinaryPoll

class DeckDetail(DetailView):
    model = Deck
    context_object_name = 'deck'

    def get_context_data(self, **kwargs):
        context = super(DeckDetail, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['user_voted'] = {poll:poll.user_voted(self.request.user) for poll in self.object.polls.all()}
            if self.object.creator == self.request.user:
                context['edit_button'] = True
                context['delete_button'] = True
            if self.request.user.has_perm('modevent.add_modevent'):
                context['edit_button'] = True
                context['delete_button'] = True
                context['content_type'] = ContentType.objects.get_for_model(Deck).pk
        return context

class DeckList(ListView):
    """List of entries, for search results.
    """
    model = Deck
    queryset = Deck.public.all()
    context_object_name = 'decks'

    def get_queryset(self):
        if self.request.GET.get('filter', False):
            self.queryset = searchQuerySet(self.queryset,
                                       self.request.GET.get('tags', False),
                                       self.request.GET.get('users', False),
                                       self.request.GET.get('fulltext', False),
                                       self.request.GET.get('date', False),
                                       self.request.GET.get('sort', SearchForm.DATE_CHOICE),
                                       self.request.GET.get('order', SearchForm.ASC_CHOICE))
        elif self.kwargs.get('search', False):
            self.queryset = self.queryset.none()
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super(DeckList, self).get_context_data(**kwargs)
        if self.kwargs.get('search', False):
            context['search'] = True
            context['form'] = SearchForm()
        return context


class DeckCreate(CreateView):
    model = Deck
    form_class = DeckForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return super(DeckCreate, self).get(request, *args, **kwargs)
        else:
            return redirect_to_login(reverse('deck:create'))

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.save()
        #image_data
        imagedata = self.request.POST.get('deck', '').partition('data:image/png;base64,') #need to test
        if imagedata[1] == 'data:image/png;base64,':
            fnm = '%i_%i%s.png' % (form.instance.pk, self.request.user.pk, self.request.user.username)
            fc = SimpleUploadedFile(fnm, base64.standard_b64decode(imagedata[2]))
            try:
                form.instance.deck_image.save(fnm, fc, True)
            except: #perhaps we should instead return a self.form_invalid with proper error text in the form
                return HttpResponse(content='<reason>Upload error, could not save image.</reason>', content_type='application/xml', status=400)
        else:
            return HttpResponse(content='<reason>Upload error, could not decode image (possibly corrupted in transmission). Type=%s</reason>' % imagedata[1], content_type='application/xml', status=400)
        #this should be in this view because this is the only time we will KNOW that we need to attach these polls
        BinaryPoll.objects.create(question="Like?", poll=form.instance)
        BinaryPoll.objects.create(question="Would you buy this?", poll=form.instance)
        return super(DeckCreate, self).form_valid(form)

class DeckUpdate(UpdateView):
    model = Deck
    form_class = DeckForm

    def get_context_data(self, **kwargs):
        context = super(DeckUpdate, self).get_context_data(**kwargs)
        context['update'] = True
        return context

    def get_initial(self):
        return {'tags': ', '.join([tag.text for tag in self.object.tags.all()])}


class DeckDelete(DeleteView):
    model = Deck
    context_object_name="deck"
    success_url = reverse_lazy('deck:list')


@csrf_protect
def vote(request, pk):
    if request.is_ajax(): #should always be ajax, but we might change our minds in the future
        if request.method == 'POST':
            if request.user.is_authenticated(): #shouldn't happen, but best to check
                try:
                    poll_id = int(request.POST.get('poll_id'))
                    vote_sign = int(request.POST.get('vote_value'))
                    poll = BinaryPoll.objects.get(pk=poll_id)
                except ValueError as e:
                    return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><error>Invalid voting data: %s</error></root>' % e, content_type='application/xml', status=400)
                if vote_sign > 0:
                    poll.yes.add(request.user)
                else:
                    poll.no.add(request.user)
                return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><v_up>%i</v_up><v_down>%i</v_down></root>' % (poll.yes_count(), poll.no_count()), content_type='application/xml', status=200)
            else:
                return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><error>Unauthorized</error></root>', content_type='application/xml', status=401)
        elif request.method == 'GET':
                try:
                    poll_id = int(request.GET.get('poll_id', None))
                    poll = BinaryPoll.objects.get(pk=poll_id)
                    return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><v_up>%i</v_up><v_down>%i</v_down></root>' % (poll.yes_count(), poll.no_count()), content_type='application/xml', status=200)
                except ValueError as e:
                    return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><error>Invalid voting data: %s</error></root>' % e, content_type='application/xml', status=400)
        else:
            return HttpResponse(content='<?xml version="1.0" encoding="UTF-8" ?>\n<root><error>Invalid voting data</error></root>', content_type='application/xml', status=405)
    else:
        pass #can't happen?


def searchView(request):
    return render_to_response('search.html')

lars/views.py
from django.template import RequestContext
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404, redirect
#from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from entry.models import Deck
from discuss.models import Thread, Category

def viewHome(request):
    d = {'newboards':[], 'thread_list':[]}
    d['newboards'] = Deck.public.all().order_by('-date_posted')[0:5]
    d['thread_list'] = Thread.public.filter(category__title='News')
    return render_to_response('home.html', context_instance=RequestContext(request, d))


def viewUser(request, pk):
    u = get_object_or_404(User, pk=pk)
    d = {'submissions': Deck.public.filter(creator=u), 'activity':[], 'user':u}
    #act = get recent submissions, get recent comments, perhaps other stuff and combine and order based on date
    return render_to_response('user_profile.html', context_instance=RequestContext(request, d))


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        referer = request.POST.get('referer', 'view_all_announcements')
        if not username or not password:
            raise Http404 #maybe there's a prettier way to fail
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(referer)
            else:
                return redirect('account_disabled_page')
        else:
            return render_to_response('login_page.html', context_instance=RequestContext(request, {'referer':referer, 'status':'Login Failed! Wrong username/password combination.'}))
    elif request.method == 'GET':
        if request.user.is_authenticated(): raise Http404 #better error message needed
        else: return render_to_response('login_page.html', context_instance=RequestContext(request, {'referer':request.META.get('HTTP_REFERER', 'view_all_announcements')}))
    else: #shouldn't ever happen, but you never know when someone's gonna try a DELETE or PUT request
        raise Http404


def logout_view(request):
    if request.user.is_authenticated():
        logout(request)
        return redirect('view_home')
    else:
        raise Http404


def preferences_view(request):
    if request.user.is_authenticated():
        if request.method == 'POST': #update settings
            pass
        elif request.method == 'GET':
            return render_to_response('user_settings.html', context_instance=RequestContext(request, {}))
        else:
            raise Http404
    else:
        return redirect('login_page')
    pass


def registration_view(request):
    if request.user.is_authenticated():
        raise Http404 #return error of some sort
    if request.method == 'POST': #registering right now
        sn = request.POST.get('username')
        pw = request.POST.get('password')
        email_addi = request.POST.get('email') #do it right now lars! you know you want to!
        if User.objects.filter(email=email_addi).count() == 0:
            if User.objects.filter(username=sn).count() == 0:
                user = User.objects.create_user(sn, email_addi, pw)
                user.save()
                return redirect('registration_successful_page')
            else:
                raise Http404 #see comment for else: below this
        else: 
            raise Http404 #actually redirect with proper error of matching emails
        pass
    elif request.method == 'GET':
        return render_to_response('new_user_registration.html', context_instance=RequestContext(request, {}))
    else:
        raise Http404
    

def accountDisabled_view(request):
    pass

def flaggedComments_view(request):
    pass

lars/templates/entry/deck_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Really delete?{% endblock %}

{% block content %}
<form method="POST" action="{% url deck:delete deck.pk %}">
	{% csrf_token %}
	<input type="submit" value="Delete" />
</form>
{% endblock %} 

lars/templates/entry/deck_form.html
{% extends 'base.html' %}

{% block title %}{% if update %}Edit deck{% else %}Submit new deck{% endif %}{% endblock %}

{% block head_script %}{% endblock %}
{% block body_script %}
<script>
var GLOW = {
	{% if not update %}
	mstatus: null,
	canv: {a: null, b: null},
	ctx: {a: null, b: null},
	image: null,
	idata: null,
	bbox: {x: 0, y: 0, w:0, h:0},
	C: { //constants
		node_dim: 8,
		ms: {
			INACTIVE: 0,
			ACTIVE: 1,
			FOCUSED: 2,
			DRAGGING: 4,
			SCALING: 8,
			CROPPING: 16,
		},
	},
	{% endif %}
	view: {% if update %}1{% else %}0{% endif %},
};

function toggle_view(e) {
	if(GLOW.view == 0) {
		$('#editpage').slideUp();
		$('#previewpage').slideDown();
		$('#view_swap').val('Edit Image');
	} else {
		$('#previewpage').slideUp();
		$('#editpage').slideDown();
		$('#view_swap').val('Edit Info');
	}
	GLOW.view ^= 1;
}

function init() {
 	{% if not update %}
	GLOW.canv.a = $('#editor')[0];
 	GLOW.canv.b = $('#preview')[0];
 	GLOW.ctx.a = GLOW.canv.a.getContext('2d');
 	GLOW.ctx.b = GLOW.canv.b.getContext('2d');
 	$(window).resize(resizeCanvas);
	$(window).trigger('resize');
	$('#imagely').on('change', handleFileSelect);
	GLOW.bbox.x = (GLOW.canv.a.width - 4) / 2;
	GLOW.bbox.y = (GLOW.canv.a.height - 4) / 2;
	$('#id_deck_length_coefficient').on('keydown', resizeCanvas)
	$('#id_deck_width_coefficient').on('keydown', resizeCanvas)
	{% endif %}
 	$('#{% if update %}edit{% else %}preview{% endif %}page').hide();
}
{% if not update %}
function resizeCanvas(e) {
	GLOW.canv.a.width = Math.min($(window).width() * .5, 600); //also need to do canv.b if that shows on side
	GLOW.canv.a.height = Math.min(($(window).height() - $('#editpage').offset().top) * .8, (GLOW.image == null ? 450 : GLOW.image.i.height));
	GLOW.bbox.h = GLOW.canv.a.height - 4;
	GLOW.bbox.w = $('#id_deck_width_coefficient')[0].value/$('#id_deck_length_coefficient')[0].value * GLOW.bbox.h;
	GLOW.canv.b.width = GLOW.bbox.w - 2;
	GLOW.canv.b.height = GLOW.bbox.h - 2; 
	if(GLOW.image) { 
    		if(GLOW.image.csc < 1 && (GLOW.image.i.width < GLOW.canv.a.width || GLOW.image.i.height < GLOW.canv.a.height)) {
    			GLOW.image.csc = 1;
		}	
		if(GLOW.image.i.width >= (GLOW.canv.a.width)) { GLOW.image.csc = (GLOW.canv.a.width) / GLOW.image.i.width; }
		if(GLOW.image.i.height >= (GLOW.canv.a.height) && (GLOW.canv.a.height) / GLOW.image.i.height < GLOW.image.csc) { //more likely
			GLOW.image.csc = (GLOW.canv.a.height) / GLOW.image.i.height; 
		}
		updateScreen(e);
		$('input[type=checkbox]').on('click', updateScreen);
	}
}



function handleFileSelect(e) {
    var i = e.target.files[0];
    var r = new FileReader();
    r.onload = (function(f) {
        return (function(e) {
            var i = new Image();
            i.onload = (function() {
            GLOW.image = {i:i, x:GLOW.canv.a.width/i.width, y:GLOW.canv.a.height/i.height, r:0, csc: 1, //csc = GLOW.canv.aas scaling constant, ratio to scale image to to fit GLOW.canv.aas
                			get w() {
                				return this.i.width * this.csc; //will factor user scaling
                			}, 
                			get h() {
                				return this.i.height * this.csc;
                			}}; 
                resizeCanvas(e);
		$('#editor').on('mouseenter', handleMouse);
                $('#editor').on('mouseleave', handleMouse);
                //$('input[name=preview]').on('click', btogs);
		//$('input[name=goback]').on('click', btogs);
		$('#bgcolor').on('change', updateScreen);
             	//if mouse.in canvas.a $(editor).on click, perhaps trigger, dunno   	
            });
            i.src = e.target.result;
        });
    })(i);
    r.readAsDataURL(i);
}

function handleMouse(e) {
	var mouseInRect = (function(px, py, rx, ry, rw, rh) {
		return ((px >= rx && px <= rx + rw) && (py >= ry && py <= ry + rh));
	});
	var mouse = {
			x:e.pageX - $('#editor').offset().left,
			y:e.pageY - $('#editor').offset().top,
	};
	C = GLOW.C.ms;


	switch(e.type) {
	case 'mouseenter':
		GLOW.mstatus = C.ACTIVE;
		$('#editor').css('cursor', 'default')
				.on('mousedown', handleMouse);
		break;
	case 'mouseleave':
		//if focused, drop box and make inactive
		//may need to return to original position if preview doesnt work
		if(GLOW.mstatus == C.FOCUSED) {
			// nothing to do to drop box?
		}
		//if active, make inactive
		$('#editor').off('mousedown').off('mousemove');
		GLOW.mstatus = C.INACTIVE;
		break;
	case 'mousedown':
		//if active, pick up box, make focused
		if(GLOW.mstatus == C.ACTIVE) {
			GLOW.bbox.x = mouse.x;
			GLOW.bbox.y = mouse.y;
			$('#editor').on('mousemove', handleMouse)
					.on('mouseup', handleMouse);
			GLOW.mstatus = C.FOCUSED;
		}
		break;
	case 'mouseup':
		if(GLOW.mstatus == C.FOCUSED) {
			GLOW.mstatus = C.ACTIVE;
			$('#editor').off('mousemove');
		}
	case 'mousemove':
		//if focused, move bbox
		if(GLOW.mstatus == C.FOCUSED) {
			GLOW.bbox.x = mouse.x;
			GLOW.bbox.y = mouse.y;
		}
	default:
		break;
	}
	updateScreen();
}


function updateScreen(text_mode) { //text_mode = Boolean, should we render canvas at all?
	if(text_mode == true) { return false; }
	if(GLOW.image) {
		GLOW.ctx.a.clearRect(0,0, GLOW.canv.a.width, GLOW.canv.a.height);
		GLOW.ctx.a.save();	
//check user controlled scaling scaling
		var dx = 0, dy = 0, sx = 0, sy = 0, dw = 0, dh = 0, sh = 0, sw = 0; 
//render image
		GLOW.ctx.a.drawImage(GLOW.image.i, sx, sy, GLOW.image.i.width, GLOW.image.i.height, dx, dy, GLOW.image.w, GLOW.image.h);	
//render bbox
		GLOW.ctx.a.save()
		GLOW.ctx.a.strokeStyle = (GLOW.mstatus & GLOW.C.ms.FOCUSED) ? "#0ff" : "#F0F";
		GLOW.ctx.a.lineWidth = 1.0;
		GLOW.ctx.a.beginPath();
			GLOW.ctx.a.rect(GLOW.bbox.x - GLOW.bbox.w / 2, GLOW.bbox.y - GLOW.bbox.h / 2, GLOW.bbox.w, GLOW.bbox.h);
		GLOW.ctx.a.stroke();	
		GLOW.ctx.a.restore()
//
	
		GLOW.ctx.a.restore();
	}
	//preview
	if(GLOW.image) {
		GLOW.ctx.b.clearRect(0, 0, GLOW.canv.b.w, GLOW.canv.b.height);
		GLOW.ctx.b.putImageData(GLOW.ctx.a.getImageData(GLOW.bbox.x - GLOW.bbox.w/2 + 1, GLOW.bbox.y - GLOW.bbox.h/2 + 1, GLOW.bbox.w-1, GLOW.bbox.h-1), 0, 0);
		GLOW.img_data = GLOW.canv.b.toDataURL('image/png');
	}
	return true;
}
{% endif %}
$(document).on('ready', function() {
	init();
	$('#view_swap').on('click', toggle_view);
	{% if not update %}
	$('input[type=submit]').on('click', function() {
		//we will need to regulate size, for now, FREE FOR ALL
		if(GLOW.image) {
			$('input[name=deck]')[0].value = GLOW.canv.b.toDataURL('image/png'); 
		}
	});
	{% endif %}
});

</script>
{% endblock %}

{% block content %}
<form name="deck" method="POST" action="">
<div id="editpage">
{% if update %}
<p>If you want to edit the image itself, you must <a href="{% url deck:delete deck.pk %}">delete it</a>, and then resubmit your entry.</p>
{% else %}
<div>{{ form.errors.deck_image }}</div>
<canvas id="editor" width="450px" height="600px" css="position: relative;"> </canvas>
<canvas id="preview" width="1px" height="1px"> </canvas>
<div style="clear:none;">
{{ form.errors.deck_length_coefficient }}{{ form.deck_length_coefficient.label_tag }}{{ form.deck_length_coefficient }}
<br />
{{ form.errors.deck_width_coefficient }}{{ form.deck_width_coefficient.label_tag }}{{ form.deck_width_coefficient }}
</div>
<input type="file" id="imagely" />
{% endif %}
</div>
<input type='button' id="view_swap" value='Edit info' />
<div id="previewpage">
<span>And now for that info!</span>
	{% csrf_token %}
	<div>{{ form.errors.title }}{{ form.title.label_tag }}{{ form.title }}</div>
	<div>{{ form.errors.text}}{{ form.text.label_tag }}{{ form.text }}</div>
	<div>{{ form.errors.challenge }}{{ form.challenge.label_tag }}{{ form.challenge }}</div>
	<div>{{ form.errors.tags }}{{ form.tags.label_tag }}{{ form.tags }}</div>
	{{ form.errors }}
	{% if not update %}<input type="hidden" name="deck" value="" />{% endif %}
<input type='submit' value="Submit!" /><input type='reset' value='Clear' />
</div>
</form>
{% endblock %}

lars/templates/entry/deck_full_view.html
<img id="design" src="{{ deck.deck_image.url }}" />
<span id="title">{{ deck.title }}</span>
<div id="deck">
	<section id="information">
 	<span id="deck_credit">Submitted by <a href="{% url view_user_profile deck.creator.id %}">{{ deck.creator.username }}</a></span>
  		<br />
  		<span id="deck_description">{{ deck.text }}</span> <br />
		<span id="deck_tag_list">{% for tag in deck.tags.all %}<a class="tagLink" href="{% url tag:view tag.pk %}">{{ tag.text }}</a> {% endfor %}</span>
	</section>
	

lars/templates/entry/deck_list.html
{% extends 'base.html' %}


{% block content %}
{% if search %}
<form method="GET">
	{{ form.as_p }}
	<input type="hidden" name="filter" value="True" />
	<input type="submit" value="Submit!" /><input type="reset" value="Clear" />
</form>
{% endif %}
{% if decks %}
<ul id="decks_slice">
	{% for deck in decks %}
	<li class="deck">{% include "entry/deck_mini_view.html" %}</li>
	{% endfor %}
</ul>
{% else %}
<span>No decks found matching this query! Would you like to <a href="{% url deck:create %}">submit one</a>?</span>
{% endif %}
{% endblock %}